name: navbrasil_spat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.4
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: fonts/LeagueSpartan-Black.ttf
          weight: 900
        - asset: fonts/LeagueSpartan-Bold.ttf
          weight: 800
        - asset: fonts/LeagueSpartan-ExtraBold.ttf
          weight: 700
        - asset: fonts/LeagueSpartan-ExtraLight.ttf
          weight: 600
        - asset: fonts/LeagueSpartan-Light.ttf
          weight: 500
        - asset: fonts/LeagueSpartan-Medium.ttf
          weight: 400
        - asset: fonts/LeagueSpartan-Regular.ttf
          weight: 300
        - asset: fonts/LeagueSpartan-SemiBold.ttf
          weight: 200
        - asset: fonts/LeagueSpartan-Thin.ttf
          weight: 100
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Black.ttf
          weight: 900
        - asset: fonts/LexendDeca-Bold.ttf
          weight: 800
        - asset: fonts/LexendDeca-ExtraBold.ttf
          weight: 700
        - asset: fonts/LexendDeca-ExtraLight.ttf
          weight: 600
        - asset: fonts/LexendDeca-Light.ttf
          weight: 500
        - asset: fonts/LexendDeca-Medium.ttf
          weight: 400
        - asset: fonts/LexendDeca-Regular.ttf
          weight: 300
        - asset: fonts/LexendDeca-SemiBold.ttf
          weight: 200
        - asset: fonts/LexendDeca-Thin.ttf
          weight: 100